
# Change this directory. Where the preprocessed data will be stored
OUTPUT_DIR_PATH: /media/miguel/Elements_2024/AI_data/preprocessed_data/ePIC_preprocessed/august2025_lowgranularity_extended_eta_correctedSF_etamask_nomaxtheta_test/

TRAINING_FRACTION: 0.75
VALIDATION_FRACTION:  0.25
BATCH_SIZE: 256  
SHUFFLE_FILES: True 
NUM_PROCESSES: 2             # Number of multiple processes used while preprocessing. 
PREPROCESS_DATA: True         # If False, will use the already preprocessed data in output_dir. If True, will generate new preprocessed data
CALC_NORMALIZER_STATS: True   # If True, will calculate the means and stedvs of the data. If False, will use means.p from output_dir
NORMALIZER_SAMPLE_SIZE: 10    # Number of files used to calculate means and stdevs
REGRESSION_OUTPUT_DIMENSIONS: 3          # For now, 1 = energy only, 2 = energy + theta, 3 = energy + theta + phi
ENERGY_WEIGHT: 0.33           # Weights are only used if output_dim == 2. Apply prefactors to energy & theta terms in loss function
THETA_WEIGHT: 0.33
PHI_WEIGHT: 0.33
NUM_NEAREST_NEIGHBORS: 10     # number of nearest neighbors used in graph
HADRONIC_DETECTOR: insert     # hcal #zdc_Fe
INCLUDE_ECAL: True            # Should be false for ZDC
ROTATE_DATA: False             # Rotate data to the proton axis
USE_CLASSIFICATION: False     # If True, will use classification for pi0/gamma events. Will use the num file variables below instead of num_train_files, num_val_files above
THETA_UNITS: mrad # rad or mrad

NO_CLASSIFICATION_SETTINGS:
    PARTICLE: neutron
    TRAINING_DATA_PATH: /media/miguel/Elements_2024/AI_data/datasets/ePIC_data/epicforward_insertlowgranularity_neutron_log10continuous_1GeV-150GeV_1.273deg-5.7deg_08_06_2025
    TEST_DATA_PATH: /media/miguel/Elements_2024/AI_data/datasets/ePIC_data/epicforward_insertlowgranularity_neutron_log10discrete_1GeV-150GeV_1.273deg-5.7deg_08_06_2025
CLASSIFICATION_SETTINGS:
    REGRESSION_WEIGHT: 0.75       # Weight given to regression in loss function when classification is True
    CLASSIFICATION_WEIGHT: 0.25   # Weight given to classification in loss function when classification is True
    PARTICLE0: neutron
    PARTICLE0_TRAINING_DATA_PATH: /media/miguel/Elements/zdc_data/zdc_neutron_log10continuous_10GeV-300GeV_0.0deg-0.3deg_staggered_h4_01_26_2024
    PARTICLE0_TEST_DATA_PATH: /media/miguel/Elements/zdc_data/zdc_neutron_log10discrete_10GeV-300GeV_0.0deg-0.3deg_staggered_h4_01_26_2024
    PARTICLE1: lambda
    PARTICLE1_TRAINING_DATA_PATH: /media/miguel/Elements/zdc_data/zdc_lambdadecay_log10continuous_10GeV-250GeV_0.0deg-0.3deg_staggered_h4_04_25_2024
    PARTICLE1_TEST_DATA_PATH: /media/miguel/Elements/zdc_data/zdc_lambdadecay_log10discrete_10GeV-250GeV_0.0deg-0.23deg_staggered_h4_04_29_2024
