data:
  data_dir: /pscratch/sd/f/fernando/data_dir/
  particle_type: pion
  # num_train_files: 100
  # num_val_files: 30
  # num_test_files: 50
  num_train_files: 10
  num_val_files: 3
  num_test_files: 50
  batch_size: 2048
  shuffle: False
  num_procs: 4
  preprocess: True
  output_dir: /pscratch/sd/f/fernando/regressiononly/preprocessed
  particle_type: pion
  already_preprocessed: False
  calc_stats: True
  k: 10  # 5,10
  n_zsections: 8
  num_features: 2
  condition_zsections: True
  include_ecal: False
  hadronic_detector: hcal
model:
  block_type: deepsets
  num_blocks: 1
  num_layers: 4
  latent_size: 64
  concat_input: True
  reducer: mean
  edge_block_opt:
    use_edges: True
    use_receiver_nodes: True
    use_sender_nodes: True
    use_globals: True
  node_block_opt:
    use_received_edges: True
    use_sent_edges: False
    use_nodes: True
    use_globals: True
  global_block_opt:
    use_edges: False
    use_nodes: True
    use_globals: True
training:
  epochs: 100
  num_features: 4
  output_dim: 2
  include_ecal: False
  hadronic_detector: hcal
  learning_rate: 1.e-3
  save_dir: /pscratch/sd/f/fernando/deepsets_models/
